### PR TITLE
Added directions verticalLeft, verticalRight, horizontalTop and horizontalBottom

### PR DESCRIPTION
**Pull request by baspellis**
To allow to omit only a single direction I've added verticalLeft, verticalRight, horizontalTop and horizontalBottom. This way you can ignore only Top, Left, Bottom or Right safe area margin.

### CODE REVIEW

**Comment by miyabi** [comment]
@baspellis Thank you for PR! You are right, these direction options are necessary
. But I think they should be like 'verticalAndLeft'. Could you change?

**Comment by baspellis** [comment]
To make it consistent with 'topLeft', 'topRight', 'bottomLeft' and 'bottomRight' I think it should not be changed. Or would you also want to change this to 'topAndLeft', 'topAndRight', 'bottomAndLeft' and 'bottomAndRight'? You decide.

**Comment by miyabi** [comment]
Oh, you are right...
For compatibility 'topLeft', 'topRight', 'bottomLeft' and 'bottomRight' should not be changed, so I will add 'topAndLeft', 'topAndRight', 'bottomAndLeft' and 'bottomAndRight' after merging your PR.
Thank you.

**Comment by baspellis** [comment]
Renamed as requested.

**Pull request merged**
